  source 'https://cdn.cocoapods.org/'
  platform :ios, '13.0'

target 'TennisMoment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TennisMoment

  pod 'SnapKit', '~> 5.0.0'
  pod 'TABAnimated', '2.5.1'
  pod 'SwiftFormat/CLI', '~> 0.49'
  pod 'TMComponent', :git => 'https://github.com/RoyJoel/TMComponent.git'

  target 'TennisMomentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TennisMomentUITests' do
    # Pods for testing
  end

end
